import turtle
t=turtle.Turtle()

turtle.Screen().bgcolor("White")
board=turtle.Turtle()
board.pencolor("Black")
t.hideturtle()
t.speed("fastest")

board.fillcolor("Light Green")
board.begin_fill()
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
board.end_fill()
board.penup()
board.forward(100)
board.left(90)
board.forward(75)
board.pendown()
board.fillcolor("Light Blue")
board.begin_fill()
board.forward(200)
board.left(90)
board.forward(100)
board.left(90)
board.forward(200)
board.left(90)
board.forward(100)
board.end_fill()
board.penup()
board.right(150)
board.forward(200)
board.pendown()
board.fillcolor("Red")
board.begin_fill()
board.right(90)
board.forward(75)
board.left(60)
board.forward(75)
board.left(60)
board.forward(75)
board.left(60)
board.forward(75)
board.left(60)
board.forward(75)
board.left(60)
board.forward(75)
board.end_fill()

turtle.done()